### ISSUE TITLE
Charge will phone is off

### ISSUE THREAD

**Issue by SagiMedina** [M1cha/android_device_xiaomi_aries#10]
I think there is a problem there

**Comment by M1cha** [comment]
Can you give a more detailed description pls?
I mean exact problem which occurs and what is needed to reproduce it.

**Comment by SagiMedina** [comment]
Hi M1cha, please ShutDown your MI2 and connect it to the charger

**Comment by M1cha** [comment]
except the fact that lcd backlight turns on too early it works just fine here.

**Comment by SagiMedina** [comment]
So I guess the problem is only here. When Im connecting it to the charger I get the charging animation for second and then a snowy screen (like in the old televisions) then the phone shut it self down.

**Comment by SagiMedina** [comment]
Oh and the led doesn't turn on

**Comment by M1cha** [comment]
for me it looks very different.
I see the snow for 250ms. Then I see the charging animation. it turns off aftr 10s and then I can turn it back on with the power button(which causes 250ms snow and then 10s backlight). It's a powersaving feature.

**Comment by SagiMedina** [comment]
And the led? Is it blinks?

**Comment by M1cha** [comment]
The LED is a not supported(and non-default) feature. No LED doesn't mean that the phone isn't charging.

**Comment by SagiMedina** [comment]
Good to know! Thank you for you help!
