### ISSUE TITLE
MHL

### ISSUE THREAD

**Issue by SagiMedina** [M1cha/android_device_xiaomi_aries#11]
I know it is mentioned in the op, I thought it is a good idea to write it here also

**Comment by M1cha** [comment]
I split this into two issues because they have nothing todo with each other.

**Comment by SagiMedina** [comment]
You are absolutely right

**Comment by M1cha** [comment]
this is theoretically fixed now but after some connects/disconnects the whole phone freezes.

**Comment by M1cha** [comment]
fixed in cm-12.1
