### ISSUE TITLE
Camera+Torch+Black Screen outgoing call

### ISSUE THREAD

**Issue by gaernik** [M1cha/android_device_xiaomi_aries#13]
Hey, I flashed the 13.11.13 release on my MI2 with bootfix,wlanfix and gapps but camera and torch aren't still working and whenever I make a call the screen turns to black and I must wait for the call to end (or remove battery)

**Comment by gaernik** [comment]
I did a clean installation without bootfix(my bad), cm+gapps+wlanfix but still same problems. i have the syslog if needed

**Comment by gaernik** [comment]
Even after having installed today's release,camera is still not working :o

**Comment by M1cha** [comment]
make a screenshot of this app:
http://xiaomi.eu/community/threads/app-2013-06-12-hwinfo.20825/

on both MIUI and cm-10.2. and Give me your dmesg and logcat dumps.

**Comment by gaernik** [comment]
![miui-screenshot_2013-11-28-14-25-35](https://f.cloud.github.com/assets/6041876/1640373/925568d6-5837-11e3-83d5-16dd4597b495.png)
![cm-screenshot_2013-11-28-15-12-27](https://f.cloud.github.com/assets/6041876/1640374/927138d6-5837-11e3-9461-883c85c3648d.png)
![logcat](https://f.cloud.github.com/assets/6041876/1640378/c9763dc2-5837-11e3-9d90-aec63919a21e.jpg)
![dmesg](https://f.cloud.github.com/assets/6041876/1640379/c990cf20-5837-11e3-999e-eb51eaa7eafb.jpg)
here you go! I edited the extension of the dumps to jpg 'cause it won't let me upload txt and I have been waiting for a confirmation email on miuiandroid forums for 5 days now.

thanks!

**Comment by M1cha** [comment]
screenshots are ok but both logs are incomplete and broken

**Comment by gaernik** [comment]
save link with name and change the extension back to .txt, just worked for me!

**Comment by M1cha** [comment]
I know but  they're incomplete. dmesg starts after 61s. and logcat has just 24 lines.

**Comment by gaernik** [comment]
I run this: 
su
dmesg >/mnt/sdcard/dmesg.txt
logcat -d -v time >/mnt/sdcard/logcat.txt

from terminal emulator, am i doing something wrong?

EDIT. shall I dump the logs from MIUI or CM?

**Comment by M1cha** [comment]
from cm10.2 ofc

**Comment by gaernik** [comment]
the thing is that under cm10.2 I am not able to make windows recognise my device and can't send adb instructions, but it works fine with miui

EDIT. I did a reboot and clean dual install and camera worked only first time and only front camera, then I tried to switch to back one and it never worked again

**Comment by M1cha** [comment]
did you enable ADB and root in developer settings?

**Comment by gaernik** [comment]
I have but still no device listed after "adb devices", even tried with kill-server.
anyway I managed to get the dumps from terminal, these should be full:
https://drive.google.com/file/d/0ByGqwp4EVll2UzNrSURRUndrdkU/edit?usp=sharing
https://drive.google.com/file/d/0ByGqwp4EVll2dF9RaVJobWZONkE/edit?usp=sharing

**Comment by M1cha** [comment]
does the camera work with this experimental build?
http://xiaomi.eu/community/threads/rom-jb-4-3-cyanogenmod-10-2.22016/page-48#post-188779

**Comment by gaernik** [comment]
both camera and torch now work, great job! i'll keep testing

**Comment by M1cha** [comment]
I close this because camera and torch are fixed. If you have blackscreen issues open a new issue for this, please.
