### ISSUE TITLE
Latest update 27/11 -> The camera is not working well

### ISSUE THREAD

**Issue by SagiMedina** [M1cha/android_device_xiaomi_aries#17]
(MI2 32G, Same camera as yours M1cha)
When trying to take a shot of close object the flash get stuck when trying to focus and camera won't respond any more.
After that,if you try to open the camera from the lock-screen you won't be able connect to the camera any more. And the only way to fix it is to wipe dalvik cache.
Other then that, amazing work, as always!

**Comment by M1cha** [comment]
a simple reboot(without wiping dalvik-cache) should be enough

**Comment by SagiMedina** [comment]
Didn't work. only wiping dalvik-cache fixed it...
And unfortunately it was not a one time thing.

**Comment by SagiMedina** [comment]
Re-flushing...I will report later.

Edit: The bug is still there.
I'm rolling back to the prev version to check if it is also there.

**Comment by SagiMedina** [comment]
So, yap it is threre...will post logcat later.

**Comment by SagiMedina** [comment]
Will the last build (the experimental) fix it?

**Comment by M1cha** [comment]
no

**Comment by SagiMedina** [comment]
Someone else has the same problem?

**Comment by M1cha** [comment]
yes

**Comment by SagiMedina** [comment]
ionolinuxnoparty I don't know how it is related...?

However, it seems that m1hca managed to fix it. Looking forward for his next release.
