### ISSUE TITLE
13Mpixel not available with MI2S 32G

### ISSUE THREAD

**Issue by dexxa05** [M1cha/android_device_xiaomi_aries#18]
Hi,

13 MPixel option is not available with the MI2S 32G

Thx

**Comment by M1cha** [comment]
- does it work on latest build?
- does it work on any other cm-10.2 rom?

**Comment by dexxa05** [comment]
Not working with latest build
Yes working with 10.2

**Comment by Giangiva** [comment]
I have a MI2S 32GB, with the latest build, and I can set 13Mpixel in the camera settings.
I didn't test if the pictures are _for real_ 13 Mpixels, though.

**Comment by M1cha** [comment]
dexxa05: "Yes working with 10.2" - on which cm10.2 rom does it work?

**Comment by M1cha** [comment]
According to @Giangiva it works. However as long as @dexxa05 doesn't provide more information like logs I'll close this due to invalidity.
