### ISSUE TITLE
Sound intereference in headset + Sound Recorder

### ISSUE THREAD

**Issue by ghost** [M1cha/android_device_xiaomi_aries#19]
Sound recordings in CM 10.2 (20131127) from a headset with microphone suffer from some weird interference.

I'll try to post the sample recordings from M1cha and Ivan's and Miui ROMs somewhere and link them here. (Ivan's and Miui ROM do not have the problem.)

EDIT: the files are in my repository:
https://github.com/MiKhan1/mi2s-cm10.2-m1cha/tree/master/Sound%20Recorder%2001

**Comment by M1cha** [comment]
do you have this problem on both cm-10.2 and cm-11.0?

**Comment by ghost** [comment]
Yep. I have just tried linuxx's build [1] dated 2013-12-27 and the headset recording is the same as reported earlier.

[1] http://xiaomi.eu/community/threads/rom-cyngn-11-m1cha-linuxx-weekly-builds.23118/

**Comment by M1cha** [comment]
pls check if it's working in this experimental build:
http://d-h.st/BAL

**Comment by ghost** [comment]
The interference is gone. Thnx.
