### ISSUE TITLE
Audio starts with 4 seconds delay on received calls, ok on placed calls

### ISSUE THREAD

**Issue by Giangiva** [M1cha/android_device_xiaomi_aries#2]
When I pickup a call, for about 4 seconds I can't hear anything, then the audio starts.

**Comment by M1cha** [comment]
Should be fixed in next version. I dunno if CM update or switch to new CM kernel fixed this :P

**Comment by M1cha** [comment]
Should be fixed in latest build:
http://d-h.st/VTp

Please confirm

**Comment by Giangiva** [comment]
Yes, it is fixed in the build tagged 22 october 2013: thank you!
