### ISSUE TITLE
Telephone rilj wakelook and battery drain.

### ISSUE THREAD

**Issue by gabriel0** [M1cha/android_device_xiaomi_aries#20]
With 15/11 27/11, experimental And 30/11 release i have an battery drain causes by rilj.
Normaly after a clean flash (with cache And data wipes) all works ok until the first reboot, after that telephone rilj apears And doesn't stop until a wipe cache data flash, if i do a flash with justo wipe cache the rilj is there.

Phone: Mi2 16gb

**Comment by SagiMedina** [comment]
This is the weak spot of this ROM.
Fixing it will make it near perfect..
I'm still going to use it, hoping for solution in near future.

**Comment by SagiMedina** [comment]
It seems that he done the impossible again, M1cha found a solution for our problem: http://xiaomi.eu/community/index.php?posts/189031

http://xiaomi.eu/community/index.php?posts/189040

**Comment by M1cha** [comment]
Yep and the crazy thing is that very much devices could be affected by this.
When u google for RILJ wakelocks you'll find many results and not a single fix(just workarounds)

**Comment by SagiMedina** [comment]
I know... Hat's off my friend.

**Comment by M1cha** [comment]
fixed
