### ISSUE TITLE
Phone sound calls to high

### ISSUE THREAD

**Issue by gabriel0** [M1cha/android_device_xiaomi_aries#23]
Release of 03/12 
Issue: speaker sound in a call it's to high and the volume control + - doesn't change the sound even in the lowest.

**Comment by M1cha** [comment]
post dmesg and logcat after u tried to change the volume during a call

**Comment by gabriel0** [comment]
Could you download from here?https://docs.google.com/folder/d/0Bw7vPXLZzymARzRaeElrZTdUQW8/edit

**Comment by M1cha** [comment]
did u flash latest radio/modem image? Normally this should fix the problem

**Comment by gabriel0** [comment]
Hello M1cha yes with the last miui radio works ok.
