### ISSUE TITLE
Iphone headset, mic doesn't work

### ISSUE THREAD

**Issue by Vosje** [M1cha/android_device_xiaomi_aries#24]
Hello,

I am using your Rom, but the mic of my iPhone headset doesn't work.

I can hear my caller, but he can't hear me.

Used this headset before with miui and it worked fine there.

**Comment by ghost** [comment]
It seems I am hit by the same issue. Can you try to make a call and check if internal microphone works while the headset _is_ plugged in? (Try to get closer and farther from the phone microphone to find out if it makes any difference.)

**Comment by Vosje** [comment]
I’ve tested this, the internal mic doesn’t work when I connect my headset.

Gr, Rob

Van: MiKhan1 [mailto:notifications@github.com] 
Verzonden: donderdag 12 december 2013 11:28
Aan: M1cha/android_device_xiaomi_aries
CC: Vosje
Onderwerp: Re: [android_device_xiaomi_aries] Iphone headset, mic doesn't work (#24)

It seems I am hit by the same issue. Can you try to make a call and check if internal microphone works while the headset is plugged in? (Try to get closer and farther from the phone microphone to find out if it makes any difference.)

**Comment by M1cha** [comment]
pls check if it's working in this experimental build:
http://d-h.st/BAL

**Comment by ghost** [comment]
This resolves the bug for me.

**Comment by addadi** [comment]
I experience the same problem or like #19 (using both iphone headset and generic headset) with rom version 25/1/2014. are the changes in the experimental build mentioned a month ago integrated in the current builds?

**Comment by ghost** [comment]
Yep, headset mic does not work again. Probably related to reversal of audio HAL.

http://xiaomi.eu/community/threads/rom-kk-4-4-2014-01-25-cyanogenmod-11-0.22927/page-30#post-195661

**Comment by M1cha** [comment]
in ivans rom it doesn't work, too?
Because I use much from his code

**Comment by ghost** [comment]
Not sure where to get ivan's ROM, finally found some available for download here:
http://xiaomi.eu/community/threads/aosp-4-4-kitkat-rom-aosp-by-ivan.22682/page-10#post-195465

Calling with (single button) headset is okay - i.e. microphone works, pressing button during phone call mutes the mic as expected.

Keytest.apk shows Keycode: 79 (action=ACTION_DOWN, keyCode=KEYCODE_HEADSETHOOK, scanCode=226)

**Comment by M1cha** [comment]
check if it works again in 2014-02-05. I've imported some fixes from ivan's code.

**Comment by ghost** [comment]
in 2014-02-05: microphone on headset works, but the normal microphone on phone stopped working at all (tested also after reboot). I tried also to turn the mic on / off in dialer during the call, but no go...
Edit: I can see you've fixed that in the meantime. I will report again after a while.

**Comment by M1cha** [comment]
There was a kernel but in this build. as u can read in forums I deleted and re-uploaded the build.
Pls download and test again.

**Comment by ghost** [comment]
Both phone & headset mics seem to work fine for calling in he new build 2014-02-05. Thnx.

**Comment by addadi** [comment]
well, neither of them work for me with 5/2 rom. what do you recomend for debugging?

**Comment by M1cha** [comment]
I think I found the issue of this bug. I need someone to test this though

**Comment by jrizzoli** [comment]
I can :P
Il 13/nov/2014 12:05 "Michael Zimmermann" notifications@github.com ha
scritto:

**Comment by M1cha** [comment]
ok I'll push it to CM nightlies because what I found 100% is a bug and we'll see if it will fix this problem.

**Comment by ldanet** [comment]
Cool ! I will try it out and I'll let you know ! I really hope this will fix the problem, to me it is the only feature that misses out on CM and it is quite an important one.

**Comment by M1cha** [comment]
great that people are still interested in it. I feared that u all sold your mi2 due to this bug :D

**Comment by M1cha** [comment]
https://github.com/CyanogenMod/android_device_xiaomi_aries/commit/fd06b0e70681325caeb480e53af01d617a0b519e

It should be in the next nightly

**Comment by ldanet** [comment]
I am running today's nightly which includes your change, I don't see any difference. I tried recording my voice with the sound recorder app, it works with the built-in mic but not with the headset one.

**Comment by ldanet** [comment]
Actually I tried calling someone and he could hear me through the headset mic! I don't know why the sound recorder doesn't work with it but actually I don't really care. 

I consider this issue solved! Thanks a million!

**Comment by M1cha** [comment]
@ldanet so I treat this as being fixed. Also in the upcoming build of CM12 all these bugs should be totally gone.
