### ISSUE TITLE
Battery drain wakelock deleted_wake_locks

### ISSUE THREAD

**Issue by gabriel0** [M1cha/android_device_xiaomi_aries#25]
I have battery drain, wake lock detecor says that the deleted_wake_locks have 1.31hours when tha phone is powered on since about 1.49 hours.

**Comment by gabriel0** [comment]
I found this related "solution"

https://github.com/asksven/BetterBatteryStats-Knowledge-Base/wiki/deleted_wake_locks

**Comment by gabriel0** [comment]
Here you have an dcreen shot of wakelock detector.

https://skydrive.live.com/redir?resid=B431ADC0F5DC3A20!3126&authkey=!APM_ElruDh_b_Fc&v=3&ithint=photo%2c.png

**Comment by M1cha** [comment]
do you still have this problem?
If yes I can make a test kernel. which saves the name of all deleted wakelocks

**Comment by gabriel0** [comment]
Hello,
No i'm using your kk rom M1cha.

Thanks

**Comment by M1cha** [comment]
closed since this bugs seems to appear in cm10.2 only and I don't support this anymore
