### ISSUE TITLE
Netflix playback broken

### ISSUE THREAD

**Issue by doomedahab** [M1cha/android_device_xiaomi_aries#26]
Heavily distorted video playback in the Netflix app

**Comment by M1cha** [comment]
on which rom? cm10.2 or cm11?
if you have this problem on cm11 please try the version before latest where camera is still broken.

Unfortunately I can't test this because netflix isn't available in my country.

**Comment by doomedahab** [comment]
Latest cm11. I will revert back to the previous version like you suggest and let you know the result.

**Comment by doomedahab** [comment]
By the way, in which state does the camera need to be to test? Preview broken only, or camera broken altogether? I am now downloading the 27 dec build, which has a working camera but no preview.

**Comment by M1cha** [comment]
27 is ok

**Comment by doomedahab** [comment]
Netflix is working fine in the 27 dec. version. It seems fixing the camera broke something else :-)

**Comment by M1cha** [comment]
Damn that means the gpu driver downgrade doesn't work correctly.
Can you try to find another app with this problem?

**Comment by doomedahab** [comment]
I will check.

**Comment by doomedahab** [comment]
All other apps I have tried work, including the very similar hbo app. Youtube, imdb, all work fine.

**Comment by doomedahab** [comment]
M1cha, if you want to investigate yourself I can give you my netflix login to try. I'm sure I can trust you not to misuse ;-)

**Comment by M1cha** [comment]
That's not the problem. Netflix is fully blocked here. I can't even download the app.
I downloaded it from these apk pages but Netflix can't establish a connection to it's servers.

**Comment by doomedahab** [comment]
Ah, I see. Strange thing that Netflix is unavailable in a big country like Germany but is available to a much smaller client base here in the Netherlands. Oh well...

**Comment by M1cha** [comment]
http://d-h.st/BAL
try this. it's the audio HAL test ROM but I use the new display HAL, too.
Maybe it fixes the problem(we're still using old drivers).

Even if it works please note that it's not a daily driver rom.

**Comment by doomedahab** [comment]
Netflix playback works with this build, yay! :-) Thanks for the great work M1cha!
