### ISSUE TITLE
in call echo issue (v2014-01-03)

### ISSUE THREAD

**Issue by erlking** [M1cha/android_device_xiaomi_aries#28]
Hi,
since last CM11 update other people hear their echo really loud in call and it is almost impossible to understand me. Is there a possibility to fix it for the moment or is a downgrade more recommended?

device: Mi2 32GB

**Comment by RadarNyan** [comment]
Yeah, I got this issue too.
I can here others (who calls me) clearly but they can barely hear me because of the echo.
Was going to open an issue then I found this one, so I can confirm it's not a hardware problem.

By the way, I'm using Mi2S(16GB) standard version.

**Comment by addadi** [comment]
I'm using M1cha 3/1/2014 build from more than a week now, and these are my observations the echo problems: It happens on regular internal microphone but not with wired headset (As reported earlier that's the first build that there's no rapidly repeating ticks heard when talking through the headset). I might experienced the echo once in bad reception area with the headset but it's not an obvious case.

**Comment by erlking** [comment]
audiotest-cm11-signed.zip also didn't fix the problem for me, echo for the other person is as worse as it was before.
 ( it is from: http://xiaomi.eu/community/threads/rom-kk-4-4-2014-01-03-cyanogenmod-11-0.22927/page-24#post-194207 )

**Comment by s1rius** [comment]
+1

**Comment by M1cha** [comment]
fixed in 2012-01-21
