### ISSUE TITLE
Cannot adjust in-call audio volume: always too loud

### ISSUE THREAD

**Issue by Giangiva** [M1cha/android_device_xiaomi_aries#3]
During a call, the volume of the audio is way too high.
No way to set it lower: it's looks already at the minimum, but it's not.

**Comment by M1cha** [comment]
This is related to #2 I think.

**Comment by Giangiva** [comment]
Talking about the build tagged 22 oct 2013:
I did some quick tests and it seems to be fixed, although the volume adjustment of in call audio doesn't seem very good to me.
It has only 3-4 steps (maybe 5 but not more).
In any case, I think I'll have to test it for one or two days to see if the volume remains consistent across the calls.
Thanks in any case!

**Comment by Giangiva** [comment]
Unfortunately I didn't receive many calls yesterday and today and if I try it by myself it's not the same... :-)
Anyway, I think that the "extreme loudness" problem seems to be solved and the volume seem to remain about the same across calls.
Anyway, setting it at the minimum possible, it is still loud.
Is there any "reset" procedure I can follow to (possibly) realign the in-call volume?
I would like to be able to adjust the in-call volume in a range from "too low to hear it" up to "too loud I'm getting deaf"... :-)

**Comment by M1cha** [comment]
Can u confirm that this is fixed in 13112013 build?

**Comment by Giangiva** [comment]
Yes: it is fixed.
Sorry: I forgot to reply about it... :-(
