### ISSUE TITLE
missing kernel feature to support android-wired-tether

### ISSUE THREAD

**Issue by schlumpfschlaubi** [M1cha/android_device_xiaomi_aries#32]
i know, android comes with native tethering but android-wired-tether has some useful and needed options like configuration for network class etc.
it would be nice, if if you could build future roms with the missing kernel options (see below)
thx

---------------- http://code.google.com/p/android-wired-tether/ ----------------
Why do I get the message "Unsupported Kernel" on startup?
This means that the Linux kernel on your device does not have the features (CONFIG_NETFILTER/CONFIG_IP_NF_IPTABLES and/or RNDIS) required for tethering.

**Comment by M1cha** [comment]
it's enabled on cm-11.0 branch now(wait for today's release)
