### ISSUE TITLE
Mic and button doesn't work with Xiaomi Piston earphone

### ISSUE THREAD

**Issue by RadarNyan** [M1cha/android_device_xiaomi_aries#33]
I got the original Xiaomi Piston earphone (not the new 2.0 one, but I don't think it would make any difference on this issue)

With the latest m1cha build (2014-02-14), I found that mic doesn't work (well, I never really tried to use it before so I can't say it's the latest build caused this bug) And the buttons doesn't work as they're expected:
volume+ button: not working [in CWM recovery I can see key code is 258]
volume- button: works, but acts as volume+ [key code 257]
center button: not working [key code 256]

maybe related to issue  #24

**Comment by M1cha** [comment]
yep #24  probably is the same issue
