### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by GrantDong** [M1cha/android_device_xiaomi_aries#35]
lagging while drawing the top of the screen(about half of the status bar) on 0227 build
you would notice this by rotate the screen 90 degrees and pull down QS or just play video in any player.

![flashing](https://f.cloud.github.com/assets/3984333/2332779/37692b42-a45e-11e3-831d-3f687f4685d2.jpg)

sorry for the quality of the image... there was no time for my camera ;)

**Comment by jrizzoli** [comment]
Cm bug, don't worry

**Comment by GrantDong** [comment]
Fixed with cm-11.0 kernel branch and 0310 nightly code(just make a build to test)
