### ISSUE TITLE
Phone is not charging untill reboot

### ISSUE THREAD

**Issue by Ryotsuke** [M1cha/android_device_xiaomi_aries#36]
Sometimes phone decides not to charge from anything.
This is not very nice to find that phone was discharging all night and now you have 7% left.

It successfully gets connected to PC, I can access files, but no charge indication is seen. Phone discharges while being connected.
Connecting to power adapters make no effect either. Phone discharges while being connected.

After phone reboot it starts charging from any source.

Tested on
cm-11-20140214-UNOFFICIAL-aries
cm-11-20131229-UNOFFICIAL-aries

Xiaomi Mi2S 32Gb

USB debug is ON, ART and Dalvik

**Comment by M1cha** [comment]
should be fixed in today's release(upload will be finished soon)
