### ISSUE TITLE
after update for China Teclcom changed,not have data connection

### ISSUE THREAD

**Issue by moonlightly** [M1cha/android_device_xiaomi_aries#38]
HI, I am a mi2s user.and after update some changes for China Telecom and chinese users,It can't work for Mi2SC users which don't have data connection.This need some changes in opt/telephony?

**Comment by tomheng** [comment]
我重新编译了一个，现在不能打电话。提示：We currently accept oly US num. 怎么修改才能使用呢？

**Comment by jrizzoli** [comment]
This is a cm "bug"/feature
It's because of dialer lookup. If you are in USA it looks on some databases the name of the people is calling you and it shows it. If you're not in USA it shows we accept only us numbers. Disable people lookup in dialer settings
