### ISSUE TITLE
Mi-2s  wifi not getting enabled - 11-20140326-unofficial-aries

### ISSUE THREAD

**Issue by shikarishambu** [M1cha/android_device_xiaomi_aries#39]
I installed this ROM and while it did say "Enabling Wi-fi" it never came out of it. And, I had to "skip" it and now I can't enable wifi from settings.

I am not sure if I did something wrong.

thanks

**Comment by M1cha** [comment]
post logs please

**Comment by M1cha** [comment]
I'll reopen it as soon as you post logs
