### ISSUE TITLE
Italian operator TIM is shown as Telecom Italiz SpA

### ISSUE THREAD

**Issue by Giangiva** [M1cha/android_device_xiaomi_aries#4]
I believe there are two mistakes, here:
1) The typo: Italiz should be Italia
2) The company 'Telecom Italia SpA' is running the landline phones, in Italy, the mobile operator is TIM (http://www.tim.it), on almost all other phones, it is shown as "I TIM" ("I" stands for Italy).

btw, TIM is not just a brand, it's the largest mobile operator in Italy, with its own network.

**Comment by M1cha** [comment]
It will be renamed to "Telecom Italia SpA" but operator brandings aren't supported by qcom's native libs.
If you know a solution for how to add brandings(APN's maybe?) please tell me.

**Comment by Giangiva** [comment]
Maybe I don't understand what you mean exactly with "operator branding".
In Italy we have some operators which run their own networks (TIM, Vodafone, 3, Wind) and many others which sell SIM cards under their name but which rely on the network of one of the a.m. operators (Coop Voce, Poste Italiane, etc.) because they don't have their own network.
Are these later ones what you call "branding"?
If it is so, I'm not talking about them.
TIM (which stands for "Telecom Italia Mobile") is the largest mobile operator in Italy and it is know as "TIM", it's not a brand.
"Telecom Italia SpA", as mobile operator, simply doesn't exist.
Anyway, fixing the typo is enough for me.

**Comment by M1cha** [comment]
Should be fixed in latest build:
http://d-h.st/VTp

Please confirm

**Comment by Giangiva** [comment]
Yes, it's fixed on the build tagged 22 october 2013: thank you!

**Comment by cicciocant** [comment]
Is it possibile to know how I Can fix this issue ?
I've the same problem in antoher ROM and another Device (Resurrection Remix on LG g2)

**Comment by Giangiva** [comment]
Hi cicciocant,

there should be a lib, in your phone, whose name contains the word "ril".
I'm not sure if I remember well or not, probably its name is libqcril.so or similar.
Unfortunately, this lib is (was) closed source, so, at the time, the only way I found was to use a hex editor to hack it.
If the new name has the same length or is shorter than the actual one, the hack doesn't seem to hurt anything.

The bad news is that you have to re-hack it every time you update the firmware (if it replaces that lib).

Good luck!

Giangiva

Il 03 ottobre 2015 13:53:37 CEST, cicciocant notifications@github.com ha scritto:

> Is it possibile to know how I Can fix this issue ?
> I've the same problem in antoher ROM and another Device (Resurrection
> Remix on LG g2)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/M1cha/android_device_xiaomi_aries/issues/4#issuecomment-145242826

## 

Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by cicciocant** [comment]
Thank you.
Is this:
/system/vendor/lib/libril-qc-qmi-1.so
