### ISSUE TITLE
Spontaneous reboots

### ISSUE THREAD

**Issue by Ryotsuke** [M1cha/android_device_xiaomi_aries#41]
I'm encountering rare reboots on both 1403 and 1903 builds
M2S 32Gb

I have a feeling phone reboots at incoming call or SMS as I've got reported that I was "unavaible" at same tiems I've encountered few of that. And probability of reboot is higher in area when connection is not very good.

**Comment by M1cha** [comment]
please post logs.

**Comment by Ryotsuke** [comment]
How do I get them? Aren't they erased upon reboot?

**Comment by M1cha** [comment]
not on a soft reboot(bootanimation)
if it was a hard reboot you can dump /proc/last_ksmg immediately after the reboot.

**Comment by Ryotsuke** [comment]
This looks like hard reboot - reboots to MI-logo. Encountered this today in low-connection area
https://www.dropbox.com/s/ng621jzayy160ie/last_kmsg
I've dumped log, but it is stuck in gmail application. I can't send(Stuck in "Sending") it and can get attachments from there(nothing in app cache/downloads). Perhaps I'll attach that later

**Comment by Ryotsuke** [comment]
https://www.dropbox.com/s/f3l61sup8fc1fxw/09042014.zip
Happened one more time
This time it has stuck, not rebooted itself.

**Comment by Ryotsuke** [comment]
One more reboot, one more log
https://www.dropbox.com/s/pi5jcbfww0plqnn/12022014.zip

Is this enough?

**Comment by M1cha** [comment]
the first helpful logs, thx :)

**Comment by Ryotsuke** [comment]
https://www.dropbox.com/s/g8lpdzghjjewscg/13042014.zip One more log

**Comment by M1cha** [comment]
Do you still have this problem?
