### ISSUE TITLE
External Memory cant access

### ISSUE THREAD

**Issue by mmoscosa** [M1cha/android_device_xiaomi_aries#43]
Using:

Xiaomi Mi2s
32GB

Cant Access to my external SD memory

Camera wont open -apparently because of this-
Gallery wont open because of this (See attached photo)
Voice recordings wont work for same reason.

Have tried factory reset
Wipe cache (both types)

![photo on 5-10-14 at 12 48 am](https://cloud.githubusercontent.com/assets/1172541/2935373/d1dbaa5c-d806-11e3-9116-4b96845305ff.jpg)

**Comment by M1cha** [comment]
that's weird.
can you post the output of the command "mount"?
logcat and dmesg may be helpful too

**Comment by jjletho67** [comment]
Hi,
i've exactly the same issue.
I installed cm-11-20140518-UNOFFICIAL-birthday-aries on a MI2S with CWM recovery and true dual boot enabled.

Step to reproduce the issue are:
boot cm
settings-> Backup and Reset
Factory data reset
enable the Erase USB storage and click reset phone

After this the phone reset itself and enter in recovery mode to complete the wipe procedure.
At the next reboot the sdcard is visible but apparently no more usable by any apps

As a workaround i booted into MIUI 4.5.30 (i've true dual boot enabled) and this has solved the situation in some way. MIUI has created some folders on sdcard and, after that i rebooted again into Cyanogen and everything was ok.
This is only a workaround of course, i thing there are some problems with freshly formatted or wiped sdcard.

**Comment by M1cha** [comment]
Does this bug still occur?

**Comment by CyberRaptor** [comment]
I can confirm this issue like jjletho67  said only happens if you format internal SD card (not wipe data). It doesn't matter if you format through CM setting or CWM. So there's no way to wipe the external memory without crashing CM.
For a workaround I had to use Mi-flash and completely flash MIUI through fastboot. Then install CM without formating to get it working. Booting to MIUI and back didnt solve the problem could be because i didnt have TDB on.
Using Mi 2S
Happened in all Builds I tried even the unofficial ones.

**Comment by M1cha** [comment]
are you talking about formatting data or sdcard?

**Comment by CyberRaptor** [comment]
Formating the SD card

**Comment by CyberRaptor** [comment]
When reseting the phone through the setting (settings-> Backup and Reset->Factory data reset->enable the Erase USB storage and click reset phone) if you dont select "Erase USB storage" it will reset and wipe data (without wiping SD card) and work fine after the boot. But soon as you erase and format the SD card it stops working.

**Comment by M1cha** [comment]
cm11 isn't supported anymore.
