### ISSUE TITLE
No Force Close by Long Pressing Back

### ISSUE THREAD

**Issue by ghost** [M1cha/android_device_xiaomi_aries#46]
I'm using [ROM][KK][4.4][2014-05-18] CyanogenMod 11.0.
I loved force close option by long pressing back button under screen. But here, in buttons menu, it is absent. Is it possible to integrate it too?

**Comment by M1cha** [comment]
you can find this in the developer menu, too

**Comment by ghost** [comment]
I have used SLimRoms and other custom ROMS in previous Galaxy S I for a year and a half, and I know what it is. But I just can't find it

**Comment by ghost** [comment]
I tried to add this feature from the links in xda-developers, but it is too complicated for me
