### ISSUE TITLE
No Dev Tools app

### ISSUE THREAD

**Issue by ghost** [M1cha/android_device_xiaomi_aries#47]
I'm using [ROM][KK][4.4][2014-05-18] CyanogenMod 11.0

I have found DevTools app in settings/apps list (about 120kB), but I can't find it in apps. I tried to add it to desktop, but in the app list that could be added to desktop, it was absent. How can I find and open it?

**Comment by M1cha** [comment]
it's integrated into the developer menu

**Comment by ghost** [comment]
And where is that menu? I couldn't find it in settings page anywhere?

**Comment by M1cha** [comment]
u have to tap very often on the build number until the message "You are a developer" appears.
then you can find it in the main settings.

**Comment by ghost** [comment]
Ohh..  Thank God! Just the ROMs I used have this enabled by default.
Now, I've enabled long press back to kill app option, and the time required to keep it pressed is much. Can we change it anywhere in options (it seems to be 2 seconds, can I change it to 1 or 0.5 seconds)?

**Comment by ghost** [comment]
I tried to apply an xposed module for buttons, and make long duration press for back to kill app, but it just doesn't show in toast notification whether app was killed or just back button did ots job (for 1 sec duration)

**Comment by ghost** [comment]
By the way, I calculated, it takes 2.60 seconds to press back button to close an ongoing app. That's not an appropriate time. It has to be 1 seconds or less
