### ISSUE TITLE
Force close duration 2.60 seconds

### ISSUE THREAD

**Issue by ghost** [M1cha/android_device_xiaomi_aries#48]
I calculated by timer, that it takes 2.60 seconds to long press back button to close an ongoing app. That's not an appropriate time. It has to be 1 seconds or less. Isn't there any option to decrease time for long pressing back button?

**Comment by M1cha** [comment]
if you are a developer you code add a setting for this and push it to CM's gerrit.
But there are some xposed modules as far as I know.

**Comment by ghost** [comment]
I tried an xposed app. But the problem is when it force closes an app, the toast notification telling that application is force closed doesn't appear. I think that it just does a back action.

**Comment by ghost** [comment]
I'm not a developer. I'm just a 4 year android user, that has done many rooting & flashing actions. And none of those programs or ROMs were created by me.

**Comment by M1cha** [comment]
I would look into implementing this in xposed or CM11 but I currently don't have the time to do so, sry.
Is the toast really that important to you?

**Comment by ghost** [comment]
Actually not. I found out the way to test whether it works or not, and it worked. Thank you
