### ISSUE TITLE
Remove closed apps from recents

### ISSUE THREAD

**Issue by ghost** [M1cha/android_device_xiaomi_aries#49]
Is it possible to make apps that were force closed, to be removed from recents? For example:
- I have 3 programs in my recents, and I open a new one.
- Then, I force close that newly opened app by long pressing back button
- When I open the recents again, I don't want to see the force closed app in the recents.

I know that in development menu there is an option that makes possible force closing an app in the recents, by long pressing the app's icon in recents window. But what if I "only" want to see the "running" apps in recents, but not the ones that were opened and force closed afterwards.

Is there any option to do that?

**Comment by M1cha** [comment]
not by default, sry

**Comment by ghost** [comment]
But is it possible at all?

**Comment by M1cha** [comment]
technically yes :D
maybe with a xposed module but I don't think that sth like that exists already.

**Comment by M1cha** [comment]
Since this is about CM in general (or xposed) I'll close it because it's not Mi2 related.
