### ISSUE TITLE
Dual Boot Enabled?!

### ISSUE THREAD

**Issue by ghost** [M1cha/android_device_xiaomi_aries#50]
I can't access to my other system while in CM. I tried to enter power menu, but the reboot options are not like the one in MIUI, I don'e see reboot to other system there, even though I've enabled advanced reboot in developer options.

I also tried to enter to other system in CWM, but it also wasn't possible to reboot to other system there (I entered to other system in CWM, and pressed reboot now there).

**Comment by ghost** [comment]
I've enabled TDB before flashing both of the systems by the way

**Comment by ghost** [comment]
I could find the required menu in CWM, and  could go to other system. But shouldn't it be enabled in CM, so that I could get to other system by just clicking on the reboot to other system?

**Comment by M1cha** [comment]
MIUI allows you to reboot to the other system? that's new to me.
I'll add the feature to CM once we're official, but in the meantime you can use the dualbootswitch app:
http://d-h.st/users/M1cha/?fld_id=17499#files

**Comment by ghost** [comment]
Yes, it does. When you press the reboot button, it gives you opportunity to reboot, open bootloader, fast reboot and switch to other system (the image below is done in WIUI system, but it is also present in MIUI)

I'm trying the app provided (DualbootSwitch), and it does the job. Thanks. But of course it would be better if it was implemented into ROM.
![screenshot_2014-05-25-16-43-50](https://cloud.githubusercontent.com/assets/7677834/3077084/efd93610-e412-11e3-9bd3-17e2c9ac0fa5.png)

**Comment by M1cha** [comment]
I close this now because I won't fix it.
There is a Xposed Module called AdvancedReboot which supports this and a custom Bootloader will be released soon where u will be able to select that.
