### ISSUE TITLE
Can not open voice message in WeChat

### ISSUE THREAD

**Issue by chowaikong** [M1cha/android_device_xiaomi_aries#51]
I am using the 20140518 version, just flashed it the other day and it work perfectly until I found this problem today. When I open the voice message that send from my friend in <a href="http://www.wechat.com/en/">WeChat</a>, it remian silence and fc within few second, I don't know what's wrong, please help me fix it, I am pretty rely on this app. Thanks.

**Comment by M1cha** [comment]
I need logcat to help you.

**Comment by chowaikong** [comment]
How can I find the logcat?

**Comment by M1cha** [comment]
with this app for example:
https://play.google.com/store/apps/details?id=com.js.Error

Also please note that you have to take the logs right after the error happened, because the log buffer size is limited.

**Comment by chowaikong** [comment]
Wish I didn't get the wrong file and thanks for helping me.

2014-05-29 22:14 GMT+08:00 M1cha notifications@github.com:

**Comment by chowaikong** [comment]
I have send the logcat to your email few days ago, you didn't get it ?

**Comment by M1cha** [comment]
what's your mail address? I can't find it because I get too many mails :P

**Comment by chowaikong** [comment]
I have try another app to catch the logcat and send to your email, see this time am I still get the wrong file.

**Comment by M1cha** [comment]
do you still have this problem?

**Comment by chowaikong** [comment]
I'm not using CM11 any more since this problem appear, and I didn't have time to try the new version of your ROM.
