### ISSUE TITLE
about build cm-11

### ISSUE THREAD

**Issue by npes87184** [M1cha/android_device_xiaomi_aries#52]
hello M1cha, because of wanna add my own translation to cm-11 (I have try to push it to cm official but they want me use a translation website and it is too slow and translation is bad), so I want to build it by myself.
and I git clone your device tree to cm11/device/xiaomi/aries, and kernel to cm11/kernel/xiaomi/aries
and proprietary to the cm11/vendor/xiaomi/aries.

and use : . build/envsetup.sh
brunch aries

and it finished, but when I flash it into my phone, it always in the booting animation.
what does it wrong?

thanks.

**Comment by M1cha** [comment]
you need to use this local manifest:
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="M1cha/android_device_xiaomi_aries" path="device/xiaomi/aries" remote="github" revision="tmp" />
  <project name="M1cha/android_kernel_xiaomi_aries" path="kernel/xiaomi/aries" remote="github" />
  <project name="M1cha/proprietary_vendor_xiaomi" path="vendor/xiaomi" remote="github" />
  <project path="hardware/qcom/fm" name="M1cha/android_hardware_qcom_fm" groups="qcom" remote="github" />

  <remove-project path="hardware/qcom/audio-caf" name="CyanogenMod/android_hardware_qcom_audio-caf" />
  <project path="hardware/qcom/audio-caf" name="M1cha/android_hardware_qcom_audio-caf" groups="qcom" remote="github" revision="tmp" />
</manifest>
