### ISSUE TITLE
Google Maps FC

### ISSUE THREAD

**Issue by chowaikong** [M1cha/android_device_xiaomi_aries#54]
![screenshot_2014-06-03-15-24-38](https://cloud.githubusercontent.com/assets/2826726/3157425/e4ba018c-eaf3-11e3-86cc-bdff7a39d93e.png)
I try to reinstall the app few times, and wipe out it's data, it still keep FC all the time. And I have send you the logcat to your E-mail already, you know my email.

**Comment by M1cha** [comment]
it's a GoogleMaps or CM problem:
"java.util.MissingResourceException: No 3-letter language code for locale: zz_ZZ"
