### ISSUE TITLE
proximity wake issue

### ISSUE THREAD

**Issue by erlking** [M1cha/android_device_xiaomi_aries#57]
Hi,
the proximity wake mode does really work as expected for me.
I think there is something wrong with this counter that it enables it to unlock it on the second try.

If i cover the phone it prevents maybe every 3rd try but if i use it, lock it then it immediately unlocks on the first try even if proximity is covered. 

So it happens often that i use the phone - lock it - "accidentially unlock it"  but if i leave the proximity sensor covered then it prevents unlocking the next time. - somehow wrong behaviour because it is somehow clear that it should already prevent the first "accidential unlock-try" not the second one!

it is soo weird to describe, sorry, hope you have an idea what i mean..

**Comment by M1cha** [comment]
#59
