### ISSUE TITLE
Camera crash after few seconds

### ISSUE THREAD

**Issue by Koleykus** [M1cha/android_device_xiaomi_aries#58]
I'm speaking about Google Camera.
When I open the app, camera starts focusing and app suddenly crashes.
I had this problem with nightlies 08/20 and 08/22.
I tried many gapps packs or even to download Google Camera from the store and I always had this problem.
Then I tried snapshot version (M8) and after a few crashes camera fixed by itself and now works.

**Comment by M1cha** [comment]
post logs pls

**Comment by Koleykus** [comment]
Like I said now I'm using snapshot version. Could you test if this problem
occurs to someone else (even on your own device)? If it doesn't, I will go
back to nighties and (if the problem still occurs) I will post a log.

2014-08-25 19:21 GMT+02:00 M1cha notifications@github.com:

**Comment by M1cha** [comment]
I'm on the same nightly and I don't have the problem :)
Maybe the partition size is a problem? Most mi2 users resized their partition for 4.4 or use very small gapp packages.

**Comment by Koleykus** [comment]
I extended partition (system) size too.
And I tried both small and full packages.
However, are you planning to release a new snapshot version soon (this
month)?

I'm on the same nightly and I don't have the problem :)
Maybe the partition size is a problem? Most mi2 users resized their
partition for 4.4 or use very small gapp packages.

**Comment by M1cha** [comment]
it's not up to me to release snapshots.
We'll get M9 or RC1 depending on what's next on CM's release schedule.

**Comment by Koleykus** [comment]
Now it works. I must have done something wrong while flashing the ROM the first time. Thanks.
