### ISSUE TITLE
Mi2 after start of call no sound through earpiece

### ISSUE THREAD

**Issue by ShaXiaomi** [M1cha/android_device_xiaomi_aries#60]
Hello M1cha,

after starting a phone call the voice/sound through earpiece dies or is not there.
Swichting to speaker phone sound is back again.
Again swithing to earpiece sound is back but it can go away again.

It is NOT a hardware issue. I guarantee.

I have the feeling that it is somehow related to network connection or swithcing network mode while calling. Provider is Vodafone Germany HSDPA network.

I made a VERY interesting finding:
In the moment when the voice/sound went away the Data connection (HSDPA icon) was disappearing! But could be a coincidence. Another try showed, that the HSDPA connection was also dropping but the voice stayed on.

Nexus 4 seems also to have connection issues under 4.4.4?
https://productforums.google.com/forum/#!topic/nexus/saOjkcCsPSo[1-25-false]

With WIUI 4.8.22 the problem is not occuring.

Logcat is available. Pls tell me were to send, because of private data.
Logcat was the following situation:
- Dial a number
- No ringing to hear on mobile phone's earpiece
- Landline phone rings
- Landline picks up
- Nothing to hear on mobile phone's earpiece
- Swiching mobile phone to speaker mode -> Voice/sound can be heard

Greetings
Daniel

System:
Mi2
build.board: MSM8960
build.bootloader: unknown
build.brand: Xiaomi
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: aries
build.display: cm_aries-userdebug 4.4.4 KTU84Q 548758ae10 test-keys
build.fingerprint: Xiaomi/aries/aries:4.4.2/KOT49H/937116:user/release-keys
build.hardware: aries
build.host: cyanogenmod
build.id: KTU84Q
build.manufacturer: XIAOMI
build.model: MI 2
build.product: aries
build.radio: unknown
build.serial: 4e4239a
build.tags: test-keys
build.time: 1409541354000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 548758ae10
version.release: 4.4.4
version.sdk_int: 19

**Comment by M1cha** [comment]
what is the solution?

**Comment by ShaXiaomi** [comment]
Sorry for posting in German. Did reply to the email notification and did not know it will be posted here.
Were can I send the logcat?

Hallo,

ich habe es gerade nochmal getestet und leider hat es doch nichts mit dem
Google Launcher und der Sprachsuche zu tun.
Der Bugreport ist quasi doch nicht geschlossen.
Man startet einen Anruf. Man hört es in der Ohrmuschel klingeln und nach
ein paar Sekunden ist manchmal der Ton einfach weg.
Manchmal passiert es sofort und manchmal erst noch etwa 10 Sekunden.

Ich habe hier in Logcat für dich mit folgendem Ablauf:
Mi2 ausgehnder Anruf.
Man hört es in der Ohrmuschel einmal klingeln, dann ist der Ton weg.
Umschalten auf Speaker und der Ton ist da.
Dann wieder Umschalten auf Ohrmuschel und der Ton war kurz wieder da.
Und dann auf einmal doch wieder weg.
Dann habe ich aufgelegt.

Danach ist leider ein Anruf reingekommen. Also nicht über das Log wundern.

Das Telefon ist so leider gar nicht mehr zu gebrauchen.
Das Phänomen trat auf einmal auf. Ich kann noch nicht einmal sagen, dass
ich ein Update eingespielt habe.
Evtl. hat es auch was mit dem Vodafone Netz zu tun. Eine andere SIM zum
Testen habe ich aber leider nicht da.

Vielleicht gibt es im Logcat ja etwas Ungewöhnliches zu sehen.

Beste Grüße und großen Respekt für deine Arbeit
Daniel

**Comment by ShaXiaomi** [comment]
Update:
I flashed Radio FW 3.5.17_M9615ACEFWMAZM20128017.1_qctecmdr_20130131_015319 from http://xiaomi.eu/community/threads/radio-all-xiaomi-mi2-radio-thread.19846/ and the problem was occuring.

Now I flashed Radio FW 3.2.8_M9615ACEFWMAZM20128007.1_qctecmdr_20121217_005455 and the problem seems to be gone or at least for now it is gone. 

So people who are experiencing any problems on Vodafone Germany network I would suggest to flash an older Radio FW.
