### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by maxime-poulain** [M1cha/android_device_xiaomi_aries#67]
Hello,
there are typos in device.mk file:

https://github.com/M1cha/android_device_xiaomi_aries/commit/d24c3b73a400039286fa67a54a3700cae25555bb
lline 32 "lights.mako" to delete

line  110 needs to have the white space at the end removed.
"PRODUCT_PACKAGES += \  "

**Comment by M1cha** [comment]
thx but the branch cm-12.0 is not used anymore. I started everything from scratch and we have a very clean codebase with many bugs fixed now: https://github.com/M1cha/android_device_xiaomi_aries/tree/staging/cm-12.0

**Comment by maxime-poulain** [comment]
Oh I looked to the wrong branch :D, ty
