### ISSUE TITLE
Tethering doesn't work

### ISSUE THREAD

**Issue by snoodlupa** [M1cha/android_device_xiaomi_aries#7]
I have another issue, with tethering/hotspot. I have Vodafone IT (Italy) and with MIUI all worked (obviously because MIUI is 4.1.1 and Google start block tethering on 4.1.2),but now, the tethering doesn't work. I also try with Free Tethering Fix and ISWAT Tether Unlocker.

**Comment by M1cha** [comment]
can u describe it in more detail?
- which type of tethering
- what I need to do to reproduce the problem?
- what exactly does "not work"(can't enable, u get no connection,...)?

also try latest version again because it could be a cm bug.
