### ISSUE TITLE
Lockscreen unresponsive at times, power button occasionally takes a few seconds to work.

### ISSUE THREAD

**Issue by rfilmyer** [M1cha/android_device_xiaomi_aries#70]
Occasionally, when I unlock my phone, the lock screen is extremely sluggish and my screen doesn't turn on for a few seconds. A restart will solve this problem, but it also usually it goes away by its own. I don't have to actively be using the phone in order to experience this, I could have it in my pocket for a bit. I am currently running `CM-141112-SNAPSHOT`.

What logs should I pull up next time this happens?

**Comment by jrizzoli** [comment]
It's a feature called proximity wake up. It checks proximity sensor to
avoid accidental wake ups, disable it in settings if u don't like it

Sent from my Xiaomi Mi 2S
Il 11/dic/2014 02:04 "Roger Filmyer" notifications@github.com ha scritto:

**Comment by rfilmyer** [comment]
I changed that just now in settings, I'll let you know if that solves the problem.

**Comment by rfilmyer** [comment]
Night and day difference. A question for another day is why that makes such a difference, but I'm happy.
