### ISSUE TITLE
Low volume

### ISSUE THREAD

**Issue by SagiMedina** [M1cha/android_device_xiaomi_aries#9]
The volume from speaker is not enough, and other apps like DNS manager do not work properly

**Comment by SagiMedina** [comment]
Could be fix by changing the values in:

snd_soc_msm_2x_Fusion:

SectionDevice
    Name "Speaker"
    Comment "Speaker Rx device"

```
EnableSequence
    'SLIM_0_RX Channels':0:One
    'RX3 MIX1 INP1':0:RX1
    'RX3 MIX1 INP2':0:RX6
    'RX4 DSM MUX':0:DSM_INV
    'RX3 Digital Volume':1:68
    'RX4 Digital Volume':1:68
    'LINEOUT1 Volume':1:66
    'LINEOUT3 Volume':1:66
    'SLIM TX3 MUX':0:RMIX3
    'SLIM TX5 MUX':0:RMIX5
EndSequence
```

 The lines you want to edit are:
    'RX3 Digital Volume':1:68
        'RX4 Digital Volume':1:68
To:

```
'RX3 Digital Volume':1:70
    'RX4 Digital Volume':1:70
```

**Comment by M1cha** [comment]
Are  these the new default values in MIUI? I don't want to "overclock" speaker.

**Comment by SagiMedina** [comment]
I don't know but I did it a week ago, it is not that loud but it is louder, I hardly believe it can damage the speakers, the change is minor but satisfieding
